name: langchain_dart_demo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  langchain: ^0.7.7+2
  langchain_openai: ^0.7.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
